eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例100%
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.201:3306/testsp?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: wG123456!
    initialize: true
    continueOnError: true
  rabbitmq:
    host: 192.168.1.201
    port: 5672
    username: admin
    password: admin