spring:
  profiles: primary
server:
  port: 9001
eureka:
  instance:
    hostname: eureka-primary
    port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:32002/eureka/,http://eureka-tertiary:32003/eureka/
